---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: La inteligencia artificial permite desarrollar automáticamente algoritmos
    objetivos y libres de sesgos
  checked: false
- value: Si los datos utilizados para entrenar los algoritmos de aprendizaje automático
    están sesgados, esos sesgos se transferirián al modelo resultante
  checked: true
- value: Las empresas rara vez recolectan datos de sus clientes y las personas que
    las usan
  checked: false
- value: La privacidad de la información es un problema únicamente relevante para
    altos puestos políticos y empresariales
  checked: false
name: No tan rápido
