---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: Escribir programas sencillos en Python
  checked: true
- value: Corregir faltas de ortografía
  checked: true
- value: Generar textos automáticamente
  checked: true
- value: Ofrecer asistencia a tareas rutinarias mediante comandos de voz
  checked: true
- value: Detectar fraudes bancarios
  checked: true
- value: Recomendar películas y canciones
  checked: true
- value: Traducir textos en diferentes idiomas
  checked: true
name: La máquina que aprende
