---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: La tabla `diabetes` tiene 8 columnas
  checked: false
- value: La tabla `diabetes` tiene 10 columnas
  checked: true
- value: La tabla `diabetes` tiene 11 columnas
  checked: false
- value: Es posible generar un modelo de regresión lineal simple que relacione todas
    sus variables
  checked: false
name: Un caso de estudio
