---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Los valores de la ordenada y la pendiente se mantienen constantes
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Los valores de la ordenada y la pendiente en general son menores
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "<code>R<sup>2</sup></code> se mantiene constante"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "<code>R<sup>2</sup></code> en general es menor"
  checked: true
name: Al test lo que es del test
