---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: f(x) = b × m + x
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: f(x) = b + m × x
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: f(x) = x<sup>2</sup> + x
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: f(x) = m / x + b
  checked: false
name: "¡Qué lineal y simple!"
