---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: "`body_mass_index` explica perfectamente la respuesta"
  checked: false
- value: "`body_mass_index` no explica perfectamente la respuesta"
  checked: true
name: "¿Ya llegamos al modelo?"
